name: Publish NPM Package

on:
  push:
    branches: [publish]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish npm"

    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: "7.26.0"
      - name: Install modules
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: "Publish to the npm registry"
        uses: JS-DevTools/npm-publish@v1
        env:
          token: ${{ secrets.NPM_TOKEN }}
